#copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.example.com
    extra_hosts:
      - "peer0.org1.example.com:192.168.8.25"
      - "peer1.org1.example.com:192.168.8.26"
#      - "peer0.org2.example.com:192.168.8.28"
      - "peer1.org2.example.com:192.168.8.8"
      - "orderer.example.com:192.168.8.26"
      - "orderer1.example.com:192.168.8.28"
      - "orderer2.example.com:192.168.8.8"
