# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  zookeeper2:
    container_name: zookeeper2
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    extra_hosts:
      - "zookeeper0:192.168.8.23"
      - "zookeeper1:192.168.8.27"
#      - "zookeeper2:192.168.8.25"
      - "kafka0:192.168.8.23"
      - "kafka1:192.168.8.27"
      - "kafka2:192.168.8.25"
      - "kafka3:192.168.8.26"
