#copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  kafka3:
    container_name: kafka3
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    extra_hosts:
      - "zookeeper0:192.168.8.23"
      - "zookeeper1:192.168.8.27"
      - "zookeeper2:192.168.8.25"
      - "kafka0:192.168.8.23"
      - "kafka1:192.168.8.27"
      - "kafka2:192.168.8.25"
      - "kafka3:192.168.8.26"
